### ISSUE TITLE
本

### ISSUE THREAD

**Issue by pamelankem** [jzyong/GameAI4j#1]

**Comment by jzyong** [comment]
不做棋牌游戏&nbsp;


蒋志勇
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pamela ***@***.***&gt;; 
发送时间: 2022年9月26日(星期一) 凌晨5:09
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: [jzyong/GameAI4j] 49游戏脚本 (Issue #1)





 
你好姜志勇 @jzyong
 我想聘请您为我创建一个简单的游戏解决方案。
 基本上有我在网上玩的这个有趣的在线爱好游戏
 49 场比赛（https://logigames.bet9ja.com/Games/Launcher?gameId=11000&amp;provider=0&amp;sid=&amp;pff=1&amp;skin=201）
 从 49 个数字中选择 6 个准确的数字，这些数字将在游戏结束时显示。
 5 秒的游戏红色闪烁计时器意味着无法选择数字，这意味着游戏玩家有 40 秒的时间选择数字。
 目标：我需要一个脚本或策略来找到下一个要显示的 6 个数字序列
 注意：脚本或应用程序可以实时在线或在线托管我将支付每月托管费用和维护费用
 （我先付你35,000元人民币）
 我在等你的回复 @jzyong
 谢谢你
 ***@***.***
